name: CI
on:
    push:
      branches:
        - main
      paths-ignore:
        - '**.md'
        - 'contrib/**'
        - '.github/CODEOWNERS'
    pull_request:
      branches:
        - main
      paths-ignore:
        - '**.md'
        - 'contrib/**'
        - '.github/CODEOWNERS'
    workflow_dispatch:
env:
  GO_VERSION: '1.21.12'

jobs:
    unit-test-ubuntu:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/setup-go@v5
            with:
              go-version: ${{ env.GO_VERSION }}
          - name: Checkout finch-deamon repo
            uses: actions/checkout@v4
          - name: Build and run unit tests
            run: |
             VERSION=0.8.0 make build
             make run-unit-tests