name: test
on:
    push:
      branches:
        - main
      paths-ignore:
        - '**.md'
        - 'contrib/**'
        - '.github/CODEOWNERS'
    pull_request:
      branches:
        - main
      paths-ignore:
        - '**.md'
        - 'contrib/**'
        - '.github/CODEOWNERS'
    workflow_dispatch:
env:
  GO_VERSION: '1.21.12'
  NERDCTL_VERSION: '1.7.6'
  CONTAINERD_VERSION: '1.7.18'

jobs:
    # unit-test-ubuntu:
    #     runs-on: ubuntu-latest
    #     steps:
    #       - uses: actions/setup-go@v5
    #         with:
    #           go-version: ${{ env.GO_VERSION }}
    #       - name: Checkout finch-deamon repo
    #         uses: actions/checkout@v4
    #       - name: Build and run unit tests
    #         run: |
    #          VERSION=0.8.0 make build
    #          make run-unit-tests
    git-secrets:
      runs-on: ubuntu-latest
      steps:
        - name: Pull latest awslabs/git-secrets repo
          uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
          with:
            repository: awslabs/git-secrets
            ref: 1.3.0
            fetch-tags: true
            path: git-secrets
        - name: Install git secrets from source
          run: sudo make install
          working-directory: git-secrets
        - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        - name: Scan repository for git secrets
          run: |
            git secrets --register-aws
            git secrets --scan-history
    e2e-test-macOS:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/setup-go@v5
            with:
              go-version: ${{ env.GO_VERSION }}
              cache: false
          - name: Checkout finch-daemon repo
            uses: actions/checkout@v4
          - name: Install Dependencies
            run: |
             chmod +x ./setup-test-env.sh
             ./setup-test-env.sh
          - name: Build the daemon
            run: make build
          - name: verify installed dependencies
            run: |
             nerdctl --version
             ctr -v
          - name: check if podman is present
            run: |
             sudo ls /etc/cni/net.d
             sudo rm /etc/cni/net.d/87-podman-bridge.conflist
          - name: Start finch-daemon
            run: sudo bin/finch-daemon  --debug --socket-owner $UID &
          - name: Run e2e test
            run: sudo make run-e2e-tests
