name: test
on:
    push:
      branches:
        - main
      paths-ignore:
        - '**.md'
        - 'contrib/**'
        - '.github/CODEOWNERS'
    pull_request:
      branches:
        - main
      paths-ignore:
        - '**.md'
        - 'contrib/**'
        - '.github/CODEOWNERS'
    workflow_dispatch:

jobs:
    test-mac-os:
        runs-on: macos-latest
        steps:
         - name: echo hello world
           run: echo "Hello, world"
